import { getServerSession } from "next-auth";
import "./globals.css";
import { Inter } from "next/font/google";
import Header from "@/components/header";
import Footer from "@/components/footer";
import { Toaster } from "@/components/ui/toaster";
import Provider from "@/components/provider";

const inter = Inter({ subsets: ["latin"] });



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // const session = await getServerSession();

  return (
    <html lang="en">
      <body
        className={inter.className + " h-screen flex flex-col"}
        suppressHydrationWarning={true}
      >
        <Provider>
          {/* @ts-expect-error Async Server Component */}
          <Header />

          <main className="flex-1 container mx-auto py-5 flex justify-center items-center">
            {children}
          </main>
          <Footer />
          <Toaster />
        </Provider>
      </body>
    </html>
  );
}
